[default_config]
version = "0.10.0"
assembler = "nasm"
instruction_set = "x86-64"

[default_config.opts]
compiler = "nasm"
compile_flags_txt = []
diagnostics = true
default_diagnostics = false

[[project]]
path = "ch01/hello.asm"
version = "0.10.0"
assembler = "nasm"
instruction_set = "x86-64"

[project.opts]
compiler = "nasm"
compile_flags_txt = []
diagnostics = true
default_diagnostics = true
